defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: news/:categories/:title:output_ext
      layout: "news-post"
      folder:
        path: /news/
        name: News
